<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>EasyEDA_Loader.EasyEDAShapeSvg</RootNamespace>
    <AssemblyName>EasyEDAShapeSvg.Outputer</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyEDA-Loader\EasyEDA-Loader.csproj">
      <Private>false</Private>
    </ProjectReference>
    <Reference Include="Altium.SDK">
      <HintPath>..\EasyEDA-Loader\Assemblies\Altium.SDK.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Altium.SDK.Interfaces">
      <HintPath>..\EasyEDA-Loader\Assemblies\Altium.SDK.Interfaces.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
