<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>EasyEDA_Loader</RootNamespace>
    <AssemblyName>EasyEDA-Loader</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Altium.Controls">
      <HintPath>Assemblies\Altium.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Altium.SDK">
      <HintPath>Assemblies\Altium.SDK.dll</HintPath>
    </Reference>
    <Reference Include="Altium.SDK.Interfaces">
      <HintPath>Assemblies\Altium.SDK.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Data.v24.1">
      <HintPath>Assemblies\DevExpress.Data.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Mvvm.v24.1">
      <HintPath>Assemblies\DevExpress.Mvvm.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Printing.v24.1.Core">
      <HintPath>Assemblies\DevExpress.Printing.v24.1.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Utils.v24.1">
      <HintPath>Assemblies\DevExpress.Utils.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraEditors.v24.1">
      <HintPath>Assemblies\DevExpress.XtraEditors.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v24.1">
      <HintPath>Assemblies\DevExpress.Xpf.Core.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v24.1.Core">
      <HintPath>Assemblies\DevExpress.Xpf.Grid.v24.1.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v24.1">
      <HintPath>Assemblies\DevExpress.Xpf.Grid.v24.1.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>packages\Newtonsoft.Json.13.0.3\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
