<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\TronstolE1Pnp\TronstolE1Csv.cs" Link="TronstolE1Csv.cs" />
    <Compile Include="..\..\TronstolE1Pnp\TronstolE1PartNumber.cs" Link="TronstolE1PartNumber.cs" />
    <Compile Include="..\..\TronstolE1Pnp\TronstolE1Settings.cs" Link="TronstolE1Settings.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Altium.SDK.Interfaces">
      <HintPath>..\..\EasyEDA-Loader\Assemblies\Altium.SDK.Interfaces.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
